### ISSUE TITLE
I've just spotted that you are using outdated Kotlin version ;)

### ISSUE THREAD

**Issue by wendigo** [TouK/krush-example#1]
https://github.com/TouK/krush-example/blob/a01b9d64d9a223fee10c7b12f5870b6d8a275a52/build.gradle.kts#L5

Please upgrade to 1.3.60 (see: https://blog.jetbrains.com/kotlin/2019/11/kotlin-1-3-60-released/)

Cheers!

**Comment by pjagielski** [comment]
Thanks! Fixed in https://github.com/TouK/krush-example/commit/9e0d30f5e3ed8fdf53da2302ad3336087ea1d9f2

**Comment by wendigo** [comment]
Damn, 1.3.61 was released :)
